#!/usr/bin/env bash
# are u serious we doing this

function heart() {
	rm /var/run/myscript.pid
	exit
}

trap "echo I hate the kill command;heart" SIGTERM
trap "echo Y U no love me?!;heart" SIGINT

echo $$ >> /var/run/myscript.pid
while true
do
	echo To infinity and beyondd
done
