#!/usr/bin/env bash
# are u serious we doing this

function love() {
	rm /var/run/myscript.pid
	exit
}

trap "echo I hate to kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/mysript.pid
while true
do
	echo To infinity and beyondd
done
